# Generated by Django 4.2.5 on 2023-10-26 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('RestaurantID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('ImageURL', models.CharField(max_length=255, null=True)),
                ('Rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('Is_open', models.BooleanField(default=False)),
                ('Open_dates', models.TextField(null=True)),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('PriceLevel', models.IntegerField(blank=True, null=True)),
                ('Takeout', models.BooleanField(default=False)),
                ('Dine_in', models.BooleanField(default=False)),
                ('Delivery', models.BooleanField(default=False)),
                ('Reservable', models.BooleanField(default=False)),
                ('Serves_vegetarian_food', models.BooleanField(default=False)),
                ('Serves_wine', models.BooleanField(default=False)),
                ('Serves_beer', models.BooleanField(default=False)),
            ],
        ),
    ]
