# Generated by Django 4.2.5 on 2023-10-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_delivery_restaurant_dine_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='PriceLevel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
