# Generated by Django 4.2.5 on 2023-10-06 01:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('BookmarkID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('RestaurantID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255, null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('ImageURL', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')])),
                ('Role', models.CharField(choices=[('USER', 'user'), ('ADMIN', 'admin')], max_length=5)),
                ('Bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.bookmark')),
            ],
        ),
        migrations.AddField(
            model_name='bookmark',
            name='RestaurantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.restaurant'),
        ),
    ]
