# Generated by Django 4.2.5 on 2023-10-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_display_name_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN'), ('blogger', 'BLOGGER')], default='user', max_length=10),
        ),
    ]
