# Generated by Django 4.2.4 on 2023-10-13 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_rating'),
        ('user', '0008_customuser_display_name_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='RestaurantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
