# Generated by Django 4.2.5 on 2023-10-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_bookmark_restaurantid_delete_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
