# Generated by Django 4.2.5 on 2023-10-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emoji', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='user_reactions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
